ecommerce_project/cart/urls.py
from django.urls import path

from cart import views
app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.item_delete, name='item_delete'),

]

ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce_project/search_app/urls.py
from django.urls import path

from search_app import views
app_name = 'search_app'
urlpatterns = [
    path('search', views.SearchProduct, name='SearchProduct'),
]

ecommerce_project/shop/urls.py
from django.urls import path

from shop import views
app_name = 'shop'
urlpatterns = [
    path('', views.allprodcat, name='allprodcat'),
    path('<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatDetail'),

]

ecommerce_project/cart/models.py
from django.db import models
from shop.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:prodCatDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerce_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)

        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def item_delete(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(cart=cart, product=product)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce_project/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q


# Create your views here.
def SearchProduct(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

ecommerce_project/shop/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from shop.models import Category, Product


# Create your views here.
def allprodcat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    paginator = Paginator(products_list, 8)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'products': products})


def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart_custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Bitter:ital@1&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/53759352e9.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    welcome to your cart
{% endblock %}

{% block title %}
    Your cart
{% endblock %}

{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Your Cart is Empty!!!</h1>
            <br>
            <p class="text-center"><a href="{% url 'shop:allprodcat' %}">continue shopping</a></p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_cart_title">Welcome to your cart</h1>
            <br>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <td colspan="5">Your cart items</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-left">
                                    {{cart_item.product.name}}
                                    <br>
                                    SKU: {{cart_item.product.id}}
                                    <br>
                                    price: {{cart_item.product.price}}
                                    <br>
                                    Qty: {{cart_item.quantity}} x {{cart_item}}
                                </td>
                                <td>
                                    {{cart_item.sub_total}}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %}
                                <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>
                                    &nbsp&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                    &nbsp&nbsp;<a href="{% url 'cart:item_delete' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash-can custom_icon"></i></a>
                                </td>
                                {% else %}
                                <td>
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                    &nbsp;<a href="{% url 'cart:item_delete' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash-can custom_icon"></i></a>
                                </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <td>Checkout</td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Please review your cart items before proceeding the order payment.</td>
                </tr>
                <tr>
                    <td class="text-left">
                        Total Amount: <strong>{{total}}</strong>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'shop:allprodcat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
            </div>
        </div>
        </div>
    </div>
{% endif %}
{% endblock %}

ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
  {% if category %}
    {{category.description|truncatewords:153}}
  {% else %}
    welcome to Fashion stores where you can buy different items....
  {% endif %}
{% endblock %}

{% block title %}
  {% if category %}
    {{category.name}} - Fashion store
  {% else %}
    See Our New Collections - Fashion store
  {% endif %}
{% endblock %}

{% block content %}
  {% if category %}
    <div>
      <div class="row my_row_class">
        <div class="max-auto">
          <p><a href="{% url 'shop:allprodcat' %}">Our Collection</a></p>
        </div>
      </div>
    </div>
  {% endif %}
<div>
  {% if category %}
  <div class="container">
    <div class="max_auto">
      <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    </div><br>
    <div>
      <h1 class="text-center my_title">{{category.name}}</h1>
      <p class="text-justify">{{category.description}}</p>
    </div>  
  {% else %}
  <br>
    <div class="container">
      <img class="my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" width="100%" height="400px">
    </div><br>
    <div>
      <h1 class="text-center my_title">Our New Collections</h1><br>
      <p class="text-justify my_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. consectetur adipiscing elit, sed do eiusmod tempor
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div><br><br>
  {% endif %}
</div>

<div class="container">
  <div class="row mx_auto">
    {% for product in products.object_list %}
      <div class="my_bottom_margin col-12 col-md-4 col-sm-4 col-md-3 col-lg-3">
        <div class="card text-center" style="min-width:18rem;">
        <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" width="100px" height="300px"></a>
        <div class="card-body">
          <h4>{{product.name}}</h4>
          <p>{{product.price}}</p>
        </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="mx-auto">
    {% if products.paginator.num_pages > 1 %}
      <hr>
      <div class="text-center">
        {% for pg in products.paginator.page_range %}
          <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

ecommerce_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <center>
            <p class="text-center">&copy; copyright fashion store.All right Reserved</p>
    </center>

</div>

ecommerce_project/templates/header.html
<!--{% load static %}-->
<!--<header>-->
<!--  <center>-->
<!--    <a href="{% url 'shop:allprodcat' %}"><img src="{% static 'img/logo.png' %}" alt="logo" width="100px" height="100px"></a>-->
<!--  </center>-->
<!--</header>-->

ecommerce_project/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'shop:allprodcat' %}">
      <img src="{% static 'img/logo.png' %}" alt="logo" width="75" height="60">
      <b>FASHION STORE</b>
    </a>
  </div>
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping fa-beat" style="color: #747c8b;"></i>Cart({{item_count}})</a>
        </li>
        {% endif %}
      </ul>

      <form class="d-flex" action="{% url 'search_app:SearchProduct' %}" method="get">
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass" style="color: #6f7d95;"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{product.description|truncatewords:153}}
{% endblock %}

{% block title %}
  {% if category %}
    {{category.name}} - Fashion store
  {% endif %}
{% endblock %}

{% block content %}
<div class="row my_product_row_class">
  <div class="max_auto">
    <p><a href="{% url 'shop:allprodcat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category.name}}</a> | {{product.name}}</p>
  </div>
</div>
<div class="container">
<br>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <div class="min-width:18rem">
        <img class="my_prod_img" src="{{product.image.url}}" alt="{{product.name}}">
      </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <h3 class="my_prod_title"><b>{{product.name}}</b></h3>
        <p>{{product.price}}</p>
        <p class="my_desc_title">Product Description</p>
        <p class="text-justify my_prod_desc">{{product.description}}</p>
        {% if product.stock <= 0 %}
        <p style="color:red"><b>Out Of Stock</b></p>
        {% else %}
        <p><a href="{% url 'cart:add_cart' product.id %}" class="btn btn-primary">Add to Cart</a></p>
        {% endif %}
    </div>
  </div>
</div>
{% endblock %}

ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    welcome to Fashion stores where you can buy different items....
{% endblock %}

{% block title %}
    search
{% endblock %}

{% block content %}
<div class="text-center my_search_text">
    <p>You have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
  <div class="row mx_auto">
    {% for product in products %}
      <div class="my_bottom_margin col-12 col-md-4 col-sm-4 col-md-3 col-lg-3">
        <div class="card text-center" style="min-width:18rem;">
        <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" width="100px" height="300px"></a>
        <div class="card-body">
          <h4>{{product.name}}</h4>
          <p>{{product.price}}</p>
        </div>
        </div>
      </div>
      {% empty %}
        <div class="mx-auto">
          <p class="text-center my_search_text">0 result found</p>
        </div>
    {% endfor %}
  </div>
</div>
{% endblock %}